### ISSUE TITLE
Support for asynchronous creation of service collection

### ISSUE THREAD

**Issue by Devqon** [solidtoken/SpecFlow.DependencyInjection#101]
Hi!

I want to use `Microsoft.Extensions.DependencyInjection` in our e2e tests to make use of Microsoft's native stuff like `.AddLogging()` and follow the same practices we use in our web app codebase.

We also use `Playwright` in our project, so we need a way to register it as well to the DI container. I know that the container itself does not support async registration, but I was wondering if the creation of the `ServiceCollection` could support `async`?

The way this works with the default `BoDi` container is like this:

```csharp
[Binding]
public class PlaywrightHooks
{
    private readonly IObjectContainer _objectContainer;

    public PlaywrightHooks(IObjectContainer objectContainer) => _objectContainer = objectContainer;

    [BeforeScenario]
    public async Task RegisterPlaywright()
    {
        var playwright = await Playwright.CreateAsync();
        _objectContainer.RegisterInstanceAs(playwright);

        // Other registrations
        // ..
    }
}
```

So I guess a simple way how this would look like in this package is something like this:

```csharp
public static class Startup
{
    [ScenarioDependencies]
    public static async Task<IServiceCollection> CreateServicesAsync()
    {
        var services = new ServiceCollection();

        var playwright = await Playwright.CreateAsync();
        services.AddSingleton(playwright);

        // Other registrations
        // ..

        return services;
    }
}
```

Would this be something your package could support?

**Comment by mbhoek** [comment]
Hey @Devqon, thanks for creating this issue. Full async support has been one of my top wishes for some time now, but was blocked by async issues in the `BoDi` container (see #48). Most of these issues were to be solved in the next major release of SpecFlow (v4), for which I've done some work in the preview release of this package.

Unfortunately I do not know when the next version of SpecFlow will be released, as it seems no work is being done on it at the moment. As long as the SpecFlow project is in limbo, I'm limiting my time spent on this package.

**Comment by mbhoek** [comment]
Closing this issue because [the plugin will be donated to Reqnroll](https://github.com/solidtoken/SpecFlow.DependencyInjection/issues/106).
