### ISSUE TITLE
Port to support Reqnroll

### ISSUE THREAD

**Issue by Tiberriver256** [solidtoken/SpecFlow.DependencyInjection#106]
With [the announcement of Reqnroll](https://github.com/SpecFlowOSS/SpecFlow/issues/2719#issuecomment-1934292742) being the official fork of what used to be SpecFlow.

Can we expect this package to be upgraded to support it?

**Comment by mbhoek** [comment]
Short anwer: Yes 💯 

Long answer: This weekend I'll be looking into what it takes to [migrate this plugin to Reqnroll](https://docs.reqnroll.net/latest/guides/migrating-from-specflow.html). Reqnroll is based on SpecFlow v4, which was only in beta last time I checked, so it might involve some work. Expect an answer by Monday.

**Comment by mbhoek** [comment]
As I'd need to change the namespaces anyway, I'm considering [donating this plugin to the Reqnroll codebase](https://github.com/orgs/reqnroll/discussions/19). 
Please share your thoughts.

**Comment by Tiberriver256** [comment]
Seems like a good idea 👍 Would be fantastic for sure to see this as an official plugin

**Comment by mbhoek** [comment]
After discussion with @gasparnagy I have decided to go ahead and donate this plugin to the Reqnroll codebase as `Reqnroll.Microsoft.Extensions.DependencyInjection`. Work will be done [here](https://github.com/reqnroll/Reqnroll/pull/94).

**Comment by gasparnagy** [comment]
Thank you for your support @mbhoek!

**Comment by ecate** [comment]
Thank you so much @mbhoek ! We're currently using this plugin in our codebase and are eagerly waiting for the port to Reqnroll 🙏 so we can migrate our tests. If you don't mind me asking, do you have any rough estimate on when this might be completed?  We truly appreciate your efforts and understand that this is voluntary work !

**Comment by mbhoek** [comment]
Thanks @ecate. I understand the need for a timeline but unfortunately I'm pretty busy with my client projects right now. Working on the Reqnroll codebase has been somewhat challenging, so it's too early for a rough estimate I'm afraid. ~~Having said that, I'll try to do a weekly update (probably every Sunday) to keep you informed on progress.~~

**Comment by gasparnagy** [comment]
@mbhoek could you please make a quick summary at https://github.com/orgs/reqnroll/discussions/72 of the issues made working with the codebase challenging?

**Comment by mbhoek** [comment]
Update: nearing completion of porting BoDi (an essential component of the plugin) to Reqnroll. Expect to start porting v3.9.2 of the plugin this week.

**Comment by iunal** [comment]
Hi @mbhoek Thank you for your great effort. We are using the legacy plugin in our tests, I want to migrate our projects to Reqnroll. Would you mind giving any update about the plugin? Thanks in advance.

**Comment by mbhoek** [comment]
@iunal Work on porting the plugin has begun, but unfortunately I'm very limited in time. Subscribe to this issue to stay up to date.

**Comment by MarioMajcicaAtABNAMRO** [comment]
Do you need any help?

**Comment by mbhoek** [comment]
@MarioMajcicaAtABNAMRO ~~I am currently blocked by https://github.com/reqnroll/Reqnroll/issues/91~~.

**Comment by mbhoek** [comment]
I've created the draft PR to [add the Microsoft.Extensions.DependencyInjection integration plugin to Reqnroll](https://github.com/reqnroll/Reqnroll/pull/94).

I expect to complete this before end of month. Subscribe to the PR to be notified of updates.

**Comment by mbhoek** [comment]
This plugin is now part of [Reqnroll](http://reqnroll.net/).
