### ISSUE TITLE
Use GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by mbhoek** [solidtoken/SpecFlow.DependencyInjection#11]
As a developer, I want to move to GitHub Actions in order to:
- be more open about the process
- get experience with GitHub Actions
- don't have a dependency on a private resource

Requires:
- [x] access to (the) GitHub Actions (beta)
- [x] checkout the documentation
- [x] testing (and thus CI/CD) in a different branch than `master`
- [ ] use GitHub Releases (in the same way as SpecFlow; first publish Nuget, then release)
- [ ] add Symbol Packages to NuGet server (follow-up of #21)
- [ ] nuget package asset is missing from the GitHub Release (sometimes)
- [ ] automatically generate release notes

**Comment by mbhoek** [comment]
Account now has beta access to GitHub Actions. 
- documentation: https://help.github.com/en/categories/automating-your-workflow-with-github-actions
- learning lab: https://lab.github.com/github/hello-github-actions!

**Comment by 304NotModified** [comment]
> * don't have a dependency on a private resource

FYI, you could also have a free Azure Pipeline for open source these days (10 parallel builds!)

**Comment by mbhoek** [comment]
Abandoned in favor of Azure Pipelines.
