### ISSUE TITLE
Update documentation for v1.0 release

### ISSUE THREAD

**Issue by mbhoek** [solidtoken/SpecFlow.DependencyInjection#19]
As a maintainer, I want to update all documentation (in the broadest sense) before releasing v1.0.

- [x] README (review the setup code, make it an 'easy howto')
- [x] LICENSE (see what the impact of the new SpecFlow license is)
- [x] NuGet package description (see SpecFlow NuGet package)
- [ ] ~Complete [community profile](https://github.com/solidtoken/SpecFlow.DependencyInjection/community)~
- [x] Source code (and examples?)
- [x] Document the main exception (`Unable to find scenario dependencies! Mark a static method that returns a IServiceCollection with [ScenarioDependencies]!`)

**Comment by mbhoek** [comment]
Consider Microsoft Code of Conduct https://opensource.microsoft.com/codeofconduct/faq/

**Comment by mbhoek** [comment]
Maybe revert the description to 'SpecFlow plugin for using Microsoft.Extensions.DependencyInjection as a dependency injection framework.'. Still on the fence about this change..

**Comment by 304NotModified** [comment]
> Maybe revert the description to 'SpecFlow plugin for using Microsoft.Extensions.DependencyInjection as a dependency injection framework.'. Still on the fence about this change..

I think the current description is better.

**Comment by 304NotModified** [comment]
Almost ready for 1.0 I see, nice! 🚀
