### ISSUE TITLE
SourceLink is not working as expected

### ISSUE THREAD

**Issue by mbhoek** [solidtoken/SpecFlow.DependencyInjection#21]
As a developer (consumer), I expect SourceLink to work. This means that if I use `SpecFlow.DepencyInjection`, I want to be able to step into the source code as part of the debugging experience.

It appears that SourceLink is not working because the .pdb file cannot be found.
It appears that .pdb file cannot be found because of a 'new build system' where [.NET no longer copies the .pdb file from the NuGet package](https://github.com/dotnet/sdk/issues/1458), but only the .dll file.
I've confirmed that if you manually select the .pdb file, you will get SourceLink support; so the main bug seems to be that the .pdb file is no longer copied from the NuGet package.

Proposed solutions are to either embed the .pdb into the .dll file, or setup a separate Symbol Package (also [involves additional settings in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2019#configure-symbol-locations-and-loading-options)). Preferred approach appears to be Symbol Packages; see https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by 304NotModified** [comment]
Is this fixed by #23?

**Comment by mbhoek** [comment]
Yes, this is fixed by #23 by embedding the pdb in the dll file. The preferred approach however is to provide Symbol Packages, which will be provided as part of #11.

**Comment by phatcher** [comment]
It's a little more involved than that, see the conversation in [SourceLink](https://github.com/dotnet/sourcelink/issues/255), e.g. I might be consuming this from a private NuGet feed in a corporate or a different type of feed, and I don't know whether this scenario will pull from the symbol server as well.

**Comment by mbhoek** [comment]
True, but my counter to that would be that packages like Newtonsoft.Json also provide Symbol Packages and no embedded pdb. Now I by no means want to imply that this package will reach the enormous volume Newtonsoft.Json has, but I imagine that corporate environments already have configuration setup for those packages to work.

Having said that, my goal is to have the best developer experience and I'm kind of ambivalent how to get there; either through embedded pdb (which means larger package size) or through symbol packages (which means extra configuration).
