### ISSUE TITLE
Change license to Apache License 2.0

### ISSUE THREAD

**Issue by mbhoek** [solidtoken/SpecFlow.DependencyInjection#33]
Change license to Apache License 2.0 because of legal trademark reasons.
https://choosealicense.com/licenses/apache-2.0/

**Comment by mbhoek** [comment]
For the upcoming 1.0 release (which will support .NET 5), I intend to change the license to Apache License 2.0. As a contributor (@304NotModified, @ConnorChristie, @IvanAlekseev), please let me know if you have any objections to this change.

**Comment by 304NotModified** [comment]
What's wrong with MIT or BSD?

**Comment by mbhoek** [comment]
Nothing wrong with MIT or BSD; I was advised to switch to Apache-2.0 because I've used a legal (business) entity name in the package identifier/namespace, which can be considered a trademark, which is better protected by the aforementioned.

What's wrong with Apache 2.0?

**Comment by mbhoek** [comment]
@304NotModified Thanks for mentioning BSD; I knew about the original license, but wasn't aware of the 3-clause variant. I like how it is much cleaner than the Apache 2.0 license, and it still seems to suit my purposes. I'll have a discussion about this tomorrow and update this issue accordingly.
