### ISSUE TITLE
Request: Support for Microsoft.Extensions.DependencyInjection <= Version 3.1.18

### ISSUE THREAD

**Issue by cliveontoast** [solidtoken/SpecFlow.DependencyInjection#67]
Hi,

Thanks for creating this nuget package. My .net core 3.1 project is currently using Microsoft.Extensions.DependencyInjection Version 3.1.17. Is it possible for this nuget package to support lower versions?

When I downloaded the code and changed the line below, the tests still pass.
```
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.18" />
```

I've not tried it in anger with my existing solution however.

It's not really a big issue, as I should update my projects, as Microsoft.Extensions.DependencyInjection 5+ is compatible with .net core 3.1.

**Comment by mbhoek** [comment]
Let me investigate and I'll get back to you by EBD tomorrow.

**Comment by mbhoek** [comment]
Apologies for not getting back to you sooner @cliveontoast . I was trying to recreate your problem using the `SpecFlow.DependencyInjection.Tests` project and adding an explicit reference, but I was not able to reproduce your problem.

If you still need this to be resolved, could you create a test project and/or include the error messages you encountered?

**Comment by cliveonfmgl** [comment]
Hi,
Sorry for not replying sooner. I kept on using AdCodicem.SpecFlow.MicrosoftDependencyInjection as it was happily working. But now that's no longer maintained (fair enough, two projects doing the same thing)

Now the project is sitting on .net 6, this isn't much of an issue for me anymore either :)

Cheers,
Clive
