### ISSUE TITLE
After ScenarioContext class is used in steps, disposal fails.

### ISSUE THREAD

**Issue by VakarisL** [solidtoken/SpecFlow.DependencyInjection#68]
If steps are using ScenarioContext for context injection as described in [SpecFlow documentation](https://docs.specflow.org/projects/specflow/en/latest/Bindings/ScenarioContext.html), i.e.:
```C#
[Binding]
public class ContextInjectionScopeSteps
{
    private readonly ScenarioContext _context;

    public ContextInjectionScopeSteps(ScenarioContext context)
    {
        _context = context;
    }

    [Given(@"I have test context with number (.*)")]
    public void GivenIHaveTestContextWithNumber(int number)
    {
        _context["number"] = number;
        //or
        //_context.Set(number);
    }
}
```

then on cleanup test fails with System.InvalidOperationException : Collection was modified; enumeration operation may not execute.:
![image](https://user-images.githubusercontent.com/30654125/130476904-430546ff-653c-4b57-87f7-97da9f456dd9.png)

**Comment by mbhoek** [comment]
Thanks for your report @VakarisL . To confirm, I can only reproduce this in .NET Framework 4.61 and .NET Core 2.1 -- do you experience the same, or does it also happen in other frameworks for you?

**Comment by VakarisL** [comment]
Possibly .NET Standard 2.0 (can't confirm currently), but I believe that falls under .NET Core 2.1.

Otherwise from running tests on this repository, I've experienced the same as you.
