### ISSUE TITLE
The type 'ServiceCollection' exists in both 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.DependencyInjection, Version=3.1.0.0

### ISSUE THREAD

**Issue by saralamuralikrishna** [solidtoken/SpecFlow.DependencyInjection#90]
I have .net 6 projected and when I install this package and try to create ServiceCollection I get below error

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ServiceCollection' exists in both 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.DependencyInjection, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by daanwissing** [comment]
If you haven't solved this yet: explicitly installing the latest package (v 6.0.0) of Microsoft.Extensions.DependencyInjection solved the same issue for me.

**Comment by mbhoek** [comment]
Hm, I should probably target the `.Abstractions` of MEDI and not the actual implementation. Will investigate.

**Comment by mbhoek** [comment]
Closing this issue because [the plugin will be donated to Reqnroll](https://github.com/solidtoken/SpecFlow.DependencyInjection/issues/106).
