### ISSUE TITLE
RegisterProxyBindings does not register step context

### ISSUE THREAD

**Issue by VladislavKutsTAQA** [solidtoken/SpecFlow.DependencyInjection#91]
![image](https://user-images.githubusercontent.com/103929695/201938366-e744fa51-d99c-4441-ad94-c301b4aa15b0.png)

I got this error when tried to configure ReportPortla nuget:
TechTalk.SpecFlow.SpecFlowException: Container of the steps class has not been initialized!
at TechTalk.SpecFlow.Steps.AssertInitialized()
at TechTalk.SpecFlow.Steps.get_ScenarioContext()
at ReportPortal.SpecFlowPlugin.ReportPortalHooks.BeforeScenario()

![image](https://user-images.githubusercontent.com/103929695/201946486-267f8abb-cde0-48c5-929d-9b1e6888ae65.png)

Buy I can get StepContext from ScenarioContext

![image](https://user-images.githubusercontent.com/103929695/201946686-b4df44ad-6dea-4f93-bece-2573eed0fd5f.png)

**Comment by mbhoek** [comment]
Thanks for the report @VladislavKutsTAQA but I'm not sure how I can help you with the ReportPortal NuGet; I don't see anything relevant to our SpecFlow.DependencyInjection plugin AFAICT. Maybe they can help you at https://github.com/reportportal/agent-net-specflow ?
