### ISSUE TITLE
Evaluate [FeatureDependencies]

### ISSUE THREAD

**Issue by mbhoek** [solidtoken/SpecFlow.DependencyInjection#93]
The Autofac plugin recently introduced the `[FeatureDependencies]` attribute (https://github.com/SpecFlowOSS/SpecFlow/pull/2622).
Evaluate whether it makes sense to add this to this plugin as well.

Personally I think it makes sense to keep the way this plugin works in line with the 'main' Autofac one.

**Comment by arnaulddumez** [comment]
It's possible to get feature name inside ScenarioDependencies when I do 

         `   services.AddScoped((x) => new DbContext(options));`

For getting different database name by feature

**Comment by mbhoek** [comment]
Hello @arnaulddumez, I don't think so because you are injecting the `DbContext` before the scenario info becomes available. Maybe you can try creating the `DbContext` inside the step using SpecFlow's `ScenarioContext.ScenarioInfo` (https://docs.specflow.org/projects/specflow/en/latest/Bindings/ScenarioContext.html#scenariocontext-scenarioinfo).

Please create a new issue if you want to continue this discussion as I don't think it's relevant to this issue. Thanks!

**Comment by mbhoek** [comment]
Closing this issue because [the plugin will be donated to Reqnroll](https://github.com/solidtoken/SpecFlow.DependencyInjection/issues/106).
